on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@6
        with:
          python-version: '3.14'
      - run: pip install gradio mypy
      - run: mypy app.py
